package com.acltabontabon.launchpad.template;

import com.acltabontabon.launchpad.rules.EngineeringRule;
import com.acltabontabon.launchpad.scanner.ProjectContext;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Assembles final file content from AI-generated summaries and predefined engineering rules.
 */
public class ContextTemplateEngine {

    public List<GeneratedFile> buildFiles(
        ProjectContext ctx,
        ContextTarget target,
        String projectSummary,
        String targetSpecificContent
    ) {
        return switch (target) {
            case CLAUDE -> buildClaudeFiles(ctx, projectSummary, targetSpecificContent);
            case CURSOR -> buildCursorFiles(ctx, projectSummary, targetSpecificContent);
        };
    }

    private List<GeneratedFile> buildClaudeFiles(ProjectContext ctx, String summary, String skills) {
        var files = new ArrayList<GeneratedFile>();

        files.add(new GeneratedFile("CLAUDE.md", buildClaudeMd(ctx, summary, skills), GeneratedFile.FileKind.CONTEXT));
        files.add(new GeneratedFile(".ai/index.md", buildAiIndex(ctx), GeneratedFile.FileKind.INDEX));
        files.add(new GeneratedFile(".ai/engineering-rules.md", buildEngineeringRulesMd(), GeneratedFile.FileKind.RULES));
        files.add(new GeneratedFile(".ai/stack.md", buildStackMd(ctx), GeneratedFile.FileKind.CONTEXT));

        return files;
    }

    private List<GeneratedFile> buildCursorFiles(ProjectContext ctx, String summary, String rules) {
        var files = new ArrayList<GeneratedFile>();

        files.add(new GeneratedFile(".cursorrules", buildCursorRules(ctx, summary, rules), GeneratedFile.FileKind.CONTEXT));
        files.add(new GeneratedFile(".cursor/rules/engineering.mdc", buildCursorEngineeringRules(), GeneratedFile.FileKind.RULES));
        files.add(new GeneratedFile(".cursor/rules/stack.mdc", buildCursorStackRules(ctx), GeneratedFile.FileKind.CONTEXT));

        return files;
    }

    private String buildClaudeMd(ProjectContext ctx, String summary, String skills) {
        return """
            # %s

            > Generated by Launchpad - local AI context generator

            ## Project Overview

            %s

            ## Stack

            %s

            ## Key Files

            %s

            ## Skills

            %s

            ## Engineering Rules

            See `.ai/engineering-rules.md` for the full list of rules that apply to this project.
            """.formatted(
                ctx.name(),
                summary,
                ctx.detectedStack(),
                formatFileList(ctx.sourceFiles(), 20),
                skills
            );
    }

    private String buildAiIndex(ProjectContext ctx) {
        return """
            # Project Index - %s

            | File | Purpose |
            |------|---------|
            | `CLAUDE.md` | Main context file - start here |
            | `.ai/engineering-rules.md` | Engineering rules for this project |
            | `.ai/stack.md` | Stack details and dependency notes |
            """.formatted(ctx.name());
    }

    private String buildStackMd(ProjectContext ctx) {
        var sb = new StringBuilder();
        sb.append("# Stack - ").append(ctx.name()).append("\n\n");
        sb.append("**Detected:** ").append(ctx.detectedStack()).append("\n\n");

        if (!ctx.dependencies().isEmpty()) {
            sb.append("## Dependencies\n\n");
            ctx.dependencies().forEach(d -> sb.append("- ").append(d).append("\n"));
        }

        if (!ctx.entryPoints().isEmpty()) {
            sb.append("\n## Entry Points\n\n");
            ctx.entryPoints().forEach((k, v) -> sb.append("- **").append(k).append(":** `").append(v).append("`\n"));
        }

        return sb.toString();
    }

    private String buildCursorRules(ProjectContext ctx, String summary, String generatedRules) {
        return """
            # Cursor Rules - %s

            ## Project Context

            %s

            ## Stack
            %s

            ## Project-Specific Rules

            %s

            ## Engineering Rules

            See `.cursor/rules/engineering.mdc` for the full engineering rule set.
            """.formatted(ctx.name(), summary, ctx.detectedStack(), generatedRules);
    }

    private String buildEngineeringRulesMd() {
        var sb = new StringBuilder();
        sb.append("# Engineering Rules\n\n");
        sb.append("These rules apply to all work in this project, regardless of feature or task.\n\n");
        Arrays.stream(EngineeringRule.values()).forEach(rule -> {
            sb.append("## ").append(rule.title).append("\n\n");
            sb.append(rule.description).append("\n\n");
        });
        return sb.toString();
    }

    private String buildCursorEngineeringRules() {
        var sb = new StringBuilder();
        sb.append("---\ndescription: Engineering rules for this project\nglobs: **/*\n---\n\n");
        Arrays.stream(EngineeringRule.values()).forEach(rule ->
            sb.append("- **").append(rule.title).append(":** ").append(rule.description).append("\n")
        );
        return sb.toString();
    }

    private String buildCursorStackRules(ProjectContext ctx) {
        return """
            ---
            description: Stack and dependency context
            globs: **/*
            ---

            Stack: %s

            Dependencies: %s
            """.formatted(
                ctx.detectedStack(),
                ctx.dependencies().isEmpty() ? "none detected" : String.join(", ", ctx.dependencies().subList(0, Math.min(ctx.dependencies().size(), 15)))
            );
    }

    private String formatFileList(List<String> files, int limit) {
        var sb = new StringBuilder();
        files.stream().limit(limit).forEach(f -> sb.append("- `").append(f).append("`\n"));
        if (files.size() > limit) {
            sb.append("- ... and ").append(files.size() - limit).append(" more\n");
        }
        return sb.toString();
    }
}
