package com.acltabontabon.launchpad.config;

import java.time.Duration;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Bounds every call into the local Ollama daemon so a stalled model or a
 * hung network does not freeze the TUI thread. Two-axis budget:
 * <ul>
 *   <li>{@code connectTimeout} - TCP / HTTP connect phase. Tight by default
 *       because a non-running daemon should surface in seconds, not minutes.</li>
 *   <li>{@code readTimeout} - upper bound on the entire response. Applied at
 *       both the HTTP client layer (covers the synchronous {@code .call()} path
 *       used by the interview) and as a Reactor {@code .timeout()} on the
 *       streamed generation path.</li>
 * </ul>
 */
@ConfigurationProperties("launchpad.ai")
public record LaunchpadAiProperties(
    Duration connectTimeout,
    Duration readTimeout,
    Ollama ollama,
    Anthropic anthropic,
    Synthesis synthesis
) {

    public LaunchpadAiProperties {
        if (connectTimeout == null) connectTimeout = Duration.ofSeconds(10);
        if (readTimeout == null) readTimeout = Duration.ofMinutes(2);
        if (ollama == null) ollama = new Ollama(null);
        if (anthropic == null) anthropic = new Anthropic(null, null, null);
        if (synthesis == null) synthesis = new Synthesis(null, null, null);
    }

    /**
     * Builds a properties instance with default Ollama / Anthropic / synthesis
     * settings. Used by call-sites that only care about HTTP timeouts (tests,
     * code paths that don't synthesise). Distinct from the canonical
     * constructor so Spring's @ConfigurationProperties binding stays
     * unambiguous (Spring picks the canonical constructor, not this factory).
     */
    public static LaunchpadAiProperties ofTimeouts(Duration connectTimeout, Duration readTimeout) {
        return new LaunchpadAiProperties(connectTimeout, readTimeout, null, null, null);
    }

    /**
     * Ollama-specific knobs. {@code numCtx} sets the runtime context-window
     * size sent with every chat call. Default {@code 8192} - the model's
     * default is 4096, which silently truncates anything longer; we ship a
     * larger value as a safety guard against future prompt growth.
     */
    public record Ollama(Integer numCtx) {
        public Ollama {
            if (numCtx == null) numCtx = 8192;
        }
    }

    /**
     * Anthropic (Claude) cloud-provider knobs. Decoupled from the shared
     * {@code launchpad.ai.base-url} / {@code api-key} (which are local-oriented)
     * so selecting Anthropic does not require re-pointing the local settings.
     * <ul>
     *   <li>{@code baseUrl} - Anthropic API host. Defaults to the public cloud
     *       endpoint.</li>
     *   <li>{@code version} - the {@code anthropic-version} header sent on every
     *       request and on the health probe.</li>
     *   <li>{@code apiKey} - the vendor-specific key. Bound in
     *       {@code application.properties} from the {@code LAUNCHPAD_ANTHROPIC_API_KEY}
     *       env var; when blank the provider falls back to the shared snapshot key.</li>
     * </ul>
     */
    public record Anthropic(String baseUrl, String version, String apiKey) {
        public Anthropic {
            if (baseUrl == null || baseUrl.isBlank()) baseUrl = "https://api.anthropic.com";
            if (version == null || version.isBlank()) version = "2023-06-01";
            if (apiKey == null) apiKey = "";
        }
    }

    /**
     * Bounded local-AI synthesis. Each fragment job has a strict input and
     * output budget so a runaway prompt can never re-introduce the
     * mega-prompt failure mode (whole AGENTS.md generated by the model).
     */
    public record Synthesis(Boolean enabled, Integer maxInputChars, Integer maxOutputChars) {
        public Synthesis {
            if (enabled == null) enabled = true;
            if (maxInputChars == null) maxInputChars = 2500;
            if (maxOutputChars == null) maxOutputChars = 800;
        }
    }
}
