package com.acltabontabon.launchpad.config;

import java.time.Duration;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Bounds every call into the local Ollama daemon so a stalled model or a
 * hung network does not freeze the TUI thread. Two-axis budget:
 * <ul>
 *   <li>{@code connectTimeout} - TCP / HTTP connect phase. Tight by default
 *       because a non-running daemon should surface in seconds, not minutes.</li>
 *   <li>{@code readTimeout} - upper bound on the entire response. Applied at
 *       both the HTTP client layer (covers the synchronous {@code .call()} path
 *       used by the interview) and as a Reactor {@code .timeout()} on the
 *       streamed generation path.</li>
 * </ul>
 */
@ConfigurationProperties("launchpad.ai")
public record LaunchpadAiProperties(
    Duration connectTimeout,
    Duration readTimeout,
    Ollama ollama,
    Synthesis synthesis
) {

    public LaunchpadAiProperties {
        if (connectTimeout == null) connectTimeout = Duration.ofSeconds(10);
        if (readTimeout == null) readTimeout = Duration.ofMinutes(2);
        if (ollama == null) ollama = new Ollama(null);
        if (synthesis == null) synthesis = new Synthesis(null, null, null);
    }

    /**
     * Builds a properties instance with default Ollama / synthesis settings.
     * Used by call-sites that only care about HTTP timeouts (tests, code
     * paths that don't synthesise). Distinct from the canonical 4-arg
     * constructor so Spring's @ConfigurationProperties binding stays
     * unambiguous (Spring picks the canonical constructor, not this factory).
     */
    public static LaunchpadAiProperties ofTimeouts(Duration connectTimeout, Duration readTimeout) {
        return new LaunchpadAiProperties(connectTimeout, readTimeout, null, null);
    }

    /**
     * Ollama-specific knobs. {@code numCtx} sets the runtime context-window
     * size sent with every chat call. Default {@code 8192} - the model's
     * default is 4096, which silently truncates anything longer; we ship a
     * larger value as a safety guard against future prompt growth.
     */
    public record Ollama(Integer numCtx) {
        public Ollama {
            if (numCtx == null) numCtx = 8192;
        }
    }

    /**
     * Bounded local-AI synthesis. Each fragment job has a strict input and
     * output budget so a runaway prompt can never re-introduce the
     * mega-prompt failure mode (whole CLAUDE.md generated by the model).
     */
    public record Synthesis(Boolean enabled, Integer maxInputChars, Integer maxOutputChars) {
        public Synthesis {
            if (enabled == null) enabled = true;
            if (maxInputChars == null) maxInputChars = 2500;
            if (maxOutputChars == null) maxOutputChars = 800;
        }
    }
}
